### ISSUE TITLE
Do-not-merge/wip label added to PR which didn't require it

### ISSUE THREAD

**Issue by harshad16** [AICoE/Sefkhet-Abwy#3]
**Describe the bug**
The bot is adding the do-not-merge/work-in-progress label to various PR which actually didn't require them.

**Expected behavior**
Investigate on the reason why the bot adding that label.
Some PR's in which the behavior was observed:
 - https://github.com/thoth-station/kebechet/pull/265
 - https://github.com/AICoE/prometheus-anomaly-detector/pull/77

**Comment by 4n4nd** [comment]
All new PRs in [AICoE/log-anomaly-detector](https://github.com/AICoE/log-anomaly-detector/pull/322) as well

**Comment by goern** [comment]
Uh... Sorry for that, I thought I deployed the src with this feature turned off...

**Comment by 4n4nd** [comment]
@harshad16 we are not seeing this issue any more, you can close the issue

**Comment by harshad16** [comment]
alright.
