### ISSUE TITLE
Create new gchat thread for the day instead of a new thread for every message

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/Sefkhet-Abwy#4]
**Is your feature request related to a problem? Please describe.**
In gchat sometimes there are too many threads so searching for an older message becomes a pain.

**Describe the solution you'd like**
Maybe Sesheta could create one new thread every day and post all messages for the day in that thread, instead of a new thread for every message.

**Describe alternatives you've considered**
None, it's not a big problem, just something that I thought would make the gchat feed look cleaner

**Comment by goern** [comment]
What about a thread for each PR?

**Comment by 4n4nd** [comment]
Sure that works, but can we include the PR number in the title then?
