### ISSUE TITLE
Notify when a review for a PR is submitted

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/Sefkhet-Abwy#5]
**Is your feature request related to a problem? Please describe.**
When I submitted a review and requested changes for [this PR](https://github.com/AICoE/log-anomaly-detector/pull/347), there were no messages in the gchat group notifying about the review.
This is not a big problem, just a nice to have feature.

**Describe the solution you'd like**
Sesheta could notify the group chat when a review (requesting changes) has been submitted to a PR.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by goern** [comment]
what hangouts room? what pr?
